task_type: "xiaohongshu"
cooperative_planning: true
autonomous_execution: false
allow_follow_up_input: true
do_bing_search: false
allow_for_replans: true
max_turns: 25
model_client_configs:
  orchestrator: &ollama_qwen3_client
    provider: autogen_ext.models.openai.OpenAIChatCompletionClient
    config:
      model: qwen3
      base_url: http://localhost:11434/v1
      api_key: ollama
      max_retries: 10
      request_timeout: 300
    model_info:
      vision: false
      function_calling: true
      json_output: false
      family: "ollama"
      structured_output: false
  coder: *ollama_qwen3_client
  web_surfer: *ollama_qwen3_client
  file_surfer: *ollama_qwen3_client
  action_guard: *ollama_qwen3_client
run_without_docker: false
browser_local: false
browser_headless: true
